spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_appstore;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

app.frontend.url=http://localhost:4200

jwt.secret=DlH8035b6sJuPOK9ndSTIAxa1rtwhgBYLF7piVoCUjkvcGXzWyREme4M2fqQZN